language: node_js
node_js:
- 8
install:
  - npm i
  - pip install awscli
after_success:
  - npm run build
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
notifications:
  email: false
